### ISSUE TITLE
Composer based installation fails on Typo3 11.5.5

### ISSUE THREAD

**Issue by McKoy61** [bihor/tinyaccordion#2]
Requirements for tinyaccordion seem to end up with v11.3.3, see error message from composer:

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires quizpalme/tinyaccordion ^7.2 -> satisfiable by quizpalme/tinyaccordion[v7.2.1].
    - quizpalme/tinyaccordion v7.2.1 requires typo3/cms-core ~10.4.6 || ~11.3.1 -> found typo3/cms-core[v10.4.6, ..., v10.4.23, v11.3.1, v11.3.2, v11.3.3] but it conflicts with your root composer.json require (^11.5.0).

**Comment by bihor** [comment]
Please test now version 7.3.0.
